internal enum ARROWBTNSTATES // TypeDefIndex: 6037
{
	// Fields
	public int value__; // 0x0
	public const ARROWBTNSTATES ABS_UPNORMAL = 1;
	public const ARROWBTNSTATES ABS_UPHOT = 2;
	public const ARROWBTNSTATES ABS_UPPRESSED = 3;
	public const ARROWBTNSTATES ABS_UPDISABLED = 4;
	public const ARROWBTNSTATES ABS_DOWNNORMAL = 5;
	public const ARROWBTNSTATES ABS_DOWNHOT = 6;
	public const ARROWBTNSTATES ABS_DOWNPRESSED = 7;
	public const ARROWBTNSTATES ABS_DOWNDISABLED = 8;
	public const ARROWBTNSTATES ABS_LEFTNORMAL = 9;
	public const ARROWBTNSTATES ABS_LEFTHOT = 10;
	public const ARROWBTNSTATES ABS_LEFTPRESSED = 11;
	public const ARROWBTNSTATES ABS_LEFTDISABLED = 12;
	public const ARROWBTNSTATES ABS_RIGHTNORMAL = 13;
	public const ARROWBTNSTATES ABS_RIGHTHOT = 14;
	public const ARROWBTNSTATES ABS_RIGHTPRESSED = 15;
	public const ARROWBTNSTATES ABS_RIGHTDISABLED = 16;
	public const ARROWBTNSTATES ABS_UPHOVER = 17;
	public const ARROWBTNSTATES ABS_DOWNHOVER = 18;
	public const ARROWBTNSTATES ABS_LEFTHOVER = 19;
	public const ARROWBTNSTATES ABS_RIGHTHOVER = 20;
}
