internal enum CHECKBOXSTATES // TypeDefIndex: 6025
{
	// Fields
	public int value__; // 0x0
	public const CHECKBOXSTATES CBS_UNCHECKEDNORMAL = 1;
	public const CHECKBOXSTATES CBS_UNCHECKEDHOT = 2;
	public const CHECKBOXSTATES CBS_UNCHECKEDPRESSED = 3;
	public const CHECKBOXSTATES CBS_UNCHECKEDDISABLED = 4;
	public const CHECKBOXSTATES CBS_CHECKEDNORMAL = 5;
	public const CHECKBOXSTATES CBS_CHECKEDHOT = 6;
	public const CHECKBOXSTATES CBS_CHECKEDPRESSED = 7;
	public const CHECKBOXSTATES CBS_CHECKEDDISABLED = 8;
	public const CHECKBOXSTATES CBS_MIXEDNORMAL = 9;
	public const CHECKBOXSTATES CBS_MIXEDHOT = 10;
	public const CHECKBOXSTATES CBS_MIXEDPRESSED = 11;
	public const CHECKBOXSTATES CBS_MIXEDDISABLED = 12;
}
