public class CinemachineTriggerAction : MonoBehaviour // TypeDefIndex: 16199
{
	// Fields
	[Tooltip("Only triggers generated by objects on these layers will be considered")]
	[Header("Trigger Object Filter")]
	public LayerMask m_LayerMask; // 0x20
	[Tooltip("If set, only triggers generated by objects with this tag will be considered")]
	[TagField]
	public string m_WithTag; // 0x28
	[TagField]
	[Tooltip("Triggers generated by objects with this tag will be ignored")]
	public string m_WithoutTag; // 0x30
	[Tooltip("Skip this many trigger entries before taking action")]
	[NoSaveDuringPlay]
	public int m_SkipFirst; // 0x38
	[Tooltip("Repeat the action for all subsequent trigger entries")]
	public bool m_Repeating; // 0x3C
	public CinemachineTriggerAction.ActionSettings m_OnObjectEnter; // 0x40
	public CinemachineTriggerAction.ActionSettings m_OnObjectExit; // 0x68
	private HashSet<GameObject> m_ActiveTriggerObjects; // 0x90

	// Methods

	// RVA: 0xC2CE60 Offset: 0xC2B860 VA: 0x180C2CE60
	private bool Filter(GameObject other) { }

	// RVA: 0xC2CF20 Offset: 0xC2B920 VA: 0x180C2CF20
	private void InternalDoTriggerEnter(GameObject other) { }

	// RVA: 0xC2D030 Offset: 0xC2BA30 VA: 0x180C2D030
	private void InternalDoTriggerExit(GameObject other) { }

	// RVA: 0xC2D1D0 Offset: 0xC2BBD0 VA: 0x180C2D1D0
	private void OnTriggerEnter(Collider other) { }

	// RVA: 0xC2D210 Offset: 0xC2BC10 VA: 0x180C2D210
	private void OnTriggerExit(Collider other) { }

	// RVA: 0xC2D110 Offset: 0xC2BB10 VA: 0x180C2D110
	private void OnCollisionEnter(Collision other) { }

	// RVA: 0xC2D190 Offset: 0xC2BB90 VA: 0x180C2D190
	private void OnCollisionExit(Collision other) { }

	// RVA: 0xC2D1D0 Offset: 0xC2BBD0 VA: 0x180C2D1D0
	private void OnTriggerEnter2D(Collider2D other) { }

	// RVA: 0xC2D210 Offset: 0xC2BC10 VA: 0x180C2D210
	private void OnTriggerExit2D(Collider2D other) { }

	// RVA: 0xC2D0D0 Offset: 0xC2BAD0 VA: 0x180C2D0D0
	private void OnCollisionEnter2D(Collision2D other) { }

	// RVA: 0xC2D150 Offset: 0xC2BB50 VA: 0x180C2D150
	private void OnCollisionExit2D(Collision2D other) { }

	// RVA: 0x43CA80 Offset: 0x43B480 VA: 0x18043CA80
	private void OnEnable() { }

	// RVA: 0xC2D250 Offset: 0xC2BC50 VA: 0x180C2D250
	public void .ctor() { }
}
