public sealed class ConstraintCollection : InternalDataCollectionBase // TypeDefIndex: 12880
{
	// Fields
	private readonly DataTable _table; // 0x10
	private readonly ArrayList _list; // 0x18
	private int _defaultNameIndex; // 0x20
	private CollectionChangeEventHandler _onCollectionChanged; // 0x28
	private Constraint[] _delayLoadingConstraints; // 0x30
	private bool _fLoadForeignKeyConstraintsOnly; // 0x38

	// Properties
	protected override ArrayList List { get; }
	public Constraint Item { get; }
	internal DataTable Table { get; }
	public Constraint Item { get; }

	// Methods

	// RVA: 0x20681B0 Offset: 0x2066BB0 VA: 0x1820681B0
	internal void .ctor(DataTable table) { }

	// RVA: 0x43EFB0 Offset: 0x43D9B0 VA: 0x18043EFB0 Slot: 12
	protected override ArrayList get_List() { }

	// RVA: 0x2068260 Offset: 0x2066C60 VA: 0x182068260
	public Constraint get_Item(int index) { }

	// RVA: 0x43EFD0 Offset: 0x43D9D0 VA: 0x18043EFD0
	internal DataTable get_Table() { }

	// RVA: 0x2068380 Offset: 0x2066D80 VA: 0x182068380
	public Constraint get_Item(string name) { }

	// RVA: 0x2065DC0 Offset: 0x20647C0 VA: 0x182065DC0
	public void Add(Constraint constraint) { }

	// RVA: 0x2065E90 Offset: 0x2064890 VA: 0x182065E90
	internal void Add(Constraint constraint, bool addUniqueWhenAddingForeign) { }

	// RVA: 0x2065DD0 Offset: 0x20647D0 VA: 0x182065DD0
	public Constraint Add(string name, DataColumn[] columns, bool primaryKey) { }

	// RVA: 0x2065CC0 Offset: 0x20646C0 VA: 0x182065CC0
	private void AddUniqueConstraint(UniqueConstraint constraint) { }

	// RVA: 0x2065C40 Offset: 0x2064640 VA: 0x182065C40
	private void AddForeignKeyConstraint(ForeignKeyConstraint constraint) { }

	// RVA: 0x2066650 Offset: 0x2065050 VA: 0x182066650
	private bool AutoGenerated(Constraint constraint) { }

	// RVA: 0x2066590 Offset: 0x2064F90 VA: 0x182066590
	private void ArrayAdd(Constraint constraint) { }

	// RVA: 0x20665E0 Offset: 0x2064FE0 VA: 0x1820665E0
	private void ArrayRemove(Constraint constraint) { }

	// RVA: 0x2066630 Offset: 0x2065030 VA: 0x182066630
	internal string AssignName() { }

	// RVA: 0x2066710 Offset: 0x2065110 VA: 0x182066710
	private void BaseAdd(Constraint constraint) { }

	// RVA: 0x2066800 Offset: 0x2065200 VA: 0x182066800
	private void BaseGroupSwitch(Constraint[] oldArray, int oldLength, Constraint[] newArray, int newLength) { }

	// RVA: 0x2066A20 Offset: 0x2065420 VA: 0x182066A20
	private void BaseRemove(Constraint constraint) { }

	// RVA: 0x2066D70 Offset: 0x2065770 VA: 0x182066D70
	internal bool CanRemove(Constraint constraint, bool fThrowException) { }

	// RVA: 0x2066DA0 Offset: 0x20657A0 VA: 0x182066DA0
	public void Clear() { }

	// RVA: 0x2067370 Offset: 0x2065D70 VA: 0x182067370
	public bool Contains(string name) { }

	// RVA: 0x2067390 Offset: 0x2065D90 VA: 0x182067390
	internal bool Contains(string name, bool caseSensitive) { }

	// RVA: 0x20674C0 Offset: 0x2065EC0 VA: 0x1820674C0
	internal Constraint FindConstraint(Constraint constraint) { }

	// RVA: 0x20677F0 Offset: 0x20661F0 VA: 0x1820677F0
	internal UniqueConstraint FindKeyConstraint(DataColumn[] columns) { }

	// RVA: 0x2067930 Offset: 0x2066330 VA: 0x182067930
	internal UniqueConstraint FindKeyConstraint(DataColumn column) { }

	// RVA: 0x2067690 Offset: 0x2066090 VA: 0x182067690
	internal ForeignKeyConstraint FindForeignKeyConstraint(DataColumn[] parentColumns, DataColumn[] childColumns) { }

	// RVA: 0x20672D0 Offset: 0x2065CD0 VA: 0x1820672D0
	private static bool CompareArrays(DataColumn[] a1, DataColumn[] a2) { }

	// RVA: 0x2067A60 Offset: 0x2066460 VA: 0x182067A60
	internal int InternalIndexOf(string constraintName) { }

	// RVA: 0x2067C70 Offset: 0x2066670 VA: 0x182067C70
	private string MakeName(int index) { }

	// RVA: 0x2067D10 Offset: 0x2066710 VA: 0x182067D10
	private void OnCollectionChanged(CollectionChangeEventArgs ccevent) { }

	// RVA: 0x2067D30 Offset: 0x2066730 VA: 0x182067D30
	internal void RegisterName(string name) { }

	// RVA: 0x2067F60 Offset: 0x2066960 VA: 0x182067F60
	public void Remove(Constraint constraint) { }

	// RVA: 0x2068120 Offset: 0x2066B20 VA: 0x182068120
	internal void UnregisterName(string name) { }
}
