internal enum ExceptionArgument // TypeDefIndex: 3824
{
	// Fields
	public int value__; // 0x0
	public const ExceptionArgument obj = 0;
	public const ExceptionArgument dictionary = 1;
	public const ExceptionArgument dictionaryCreationThreshold = 2;
	public const ExceptionArgument array = 3;
	public const ExceptionArgument info = 4;
	public const ExceptionArgument key = 5;
	public const ExceptionArgument collection = 6;
	public const ExceptionArgument list = 7;
	public const ExceptionArgument match = 8;
	public const ExceptionArgument converter = 9;
	public const ExceptionArgument queue = 10;
	public const ExceptionArgument stack = 11;
	public const ExceptionArgument capacity = 12;
	public const ExceptionArgument index = 13;
	public const ExceptionArgument startIndex = 14;
	public const ExceptionArgument value = 15;
	public const ExceptionArgument count = 16;
	public const ExceptionArgument arrayIndex = 17;
	public const ExceptionArgument name = 18;
	public const ExceptionArgument mode = 19;
	public const ExceptionArgument item = 20;
	public const ExceptionArgument options = 21;
	public const ExceptionArgument view = 22;
	public const ExceptionArgument sourceBytesToCopy = 23;
	public const ExceptionArgument start = 24;
	public const ExceptionArgument pointer = 25;
	public const ExceptionArgument ownedMemory = 26;
	public const ExceptionArgument text = 27;
	public const ExceptionArgument length = 28;
	public const ExceptionArgument comparer = 29;
	public const ExceptionArgument comparable = 30;
	public const ExceptionArgument exceptions = 31;
	public const ExceptionArgument exception = 32;
	public const ExceptionArgument action = 33;
	public const ExceptionArgument comparison = 34;
	public const ExceptionArgument startSegment = 35;
	public const ExceptionArgument endSegment = 36;
	public const ExceptionArgument endIndex = 37;
	public const ExceptionArgument task = 38;
	public const ExceptionArgument source = 39;
	public const ExceptionArgument state = 40;
	public const ExceptionArgument culture = 41;
	public const ExceptionArgument destination = 42;
	public const ExceptionArgument byteOffset = 43;
	public const ExceptionArgument minimumBufferSize = 44;
	public const ExceptionArgument offset = 45;
	public const ExceptionArgument values = 46;
	public const ExceptionArgument comparisonType = 47;
	public const ExceptionArgument s = 48;
	public const ExceptionArgument input = 49;
	public const ExceptionArgument format = 50;
}
