internal enum RADIOBUTTONSTATES // TypeDefIndex: 6024
{
	// Fields
	public int value__; // 0x0
	public const RADIOBUTTONSTATES RBS_UNCHECKEDNORMAL = 1;
	public const RADIOBUTTONSTATES RBS_UNCHECKEDHOT = 2;
	public const RADIOBUTTONSTATES RBS_UNCHECKEDPRESSED = 3;
	public const RADIOBUTTONSTATES RBS_UNCHECKEDDISABLED = 4;
	public const RADIOBUTTONSTATES RBS_CHECKEDNORMAL = 5;
	public const RADIOBUTTONSTATES RBS_CHECKEDHOT = 6;
	public const RADIOBUTTONSTATES RBS_CHECKEDPRESSED = 7;
	public const RADIOBUTTONSTATES RBS_CHECKEDDISABLED = 8;
}
