internal enum SCROLLBARPARTS // TypeDefIndex: 6036
{
	// Fields
	public int value__; // 0x0
	public const SCROLLBARPARTS SBP_ARROWBTN = 1;
	public const SCROLLBARPARTS SBP_THUMBBTNHORZ = 2;
	public const SCROLLBARPARTS SBP_THUMBBTNVERT = 3;
	public const SCROLLBARPARTS SBP_LOWERTRACKHORZ = 4;
	public const SCROLLBARPARTS SBP_UPPERTRACKHORZ = 5;
	public const SCROLLBARPARTS SBP_LOWERTRACKVERT = 6;
	public const SCROLLBARPARTS SBP_UPPERTRACKVERT = 7;
	public const SCROLLBARPARTS SBP_GRIPPERHORZ = 8;
	public const SCROLLBARPARTS SBP_GRIPPERVERT = 9;
	public const SCROLLBARPARTS SBP_SIZEBOX = 10;
}
