public static class ShaderParams // TypeDefIndex: 9222
{
	// Fields
	public static int DetailOffset; // 0x0
	public static int DetailColor; // 0x4
	public static int DetailData; // 0x8
	public static int Density; // 0xC
	public static int NativeLightsMultiplier; // 0x10
	public static int APVIntensityMultiplier; // 0x14
	public static int ShadowData; // 0x18
	public static int LightDiffusionIntensity; // 0x1C
	public static int LightDiffusionPower; // 0x20
	public static int DeepObscurance; // 0x24
	public static int NoiseScale; // 0x28
	public static int SpecularThreshold; // 0x2C
	public static int SpecularIntensity; // 0x30
	public static int SpecularColor; // 0x34
	public static int NoiseFinalMultiplier; // 0x38
	public static int NoiseStrength; // 0x3C
	public static int TurbulenceAmount; // 0x40
	public static int FogOfWarCenterAdjusted; // 0x44
	public static int FogOfWarSize; // 0x48
	public static int FogOfWarCenter; // 0x4C
	public static int FogOfWarTexture; // 0x50
	public static int DistanceData; // 0x54
	public static int MaxDistanceData; // 0x58
	public static int DepthGradientTexture; // 0x5C
	public static int HeightGradientTexture; // 0x60
	public static int DetailTexture; // 0x64
	public static int RaymarchSettings; // 0x68
	public static int SunDir; // 0x6C
	public static int Color; // 0x70
	public static int MainTex; // 0x74
	public static int WindDirection; // 0x78
	public static int DetailWindDirection; // 0x7C
	public static int LightColor; // 0x80
	public static int BoundsBorder; // 0x84
	public static int BoundsExtents; // 0x88
	public static int BoundsCenter; // 0x8C
	public static int BoundsData; // 0x90
	public static int RotationInvMatrix; // 0x94
	public static int RotationMatrix; // 0x98
	public static int SurfaceCaptureMatrix; // 0x9C
	public static int SurfaceDepthTexture; // 0xA0
	public static int SurfaceData; // 0xA4
	public static int PointLightCount; // 0xA8
	public static int PointLightInsideAtten; // 0xAC
	public static int PointLightPositions; // 0xB0
	public static int PointLightColors; // 0xB4
	public static int VoidCount; // 0xB8
	public static int VoidSizes; // 0xBC
	public static int VoidPositions; // 0xC0
	public static int VoidMatrices; // 0xC4
	public const string CustomDepthTextureName = "_CustomDepthTexture";
	public static int CustomDepthTexture; // 0xC8
	public static int CustomDepthAlphaCutoff; // 0xCC
	public static int CustomDepthBaseMap; // 0xD0
	public static int SpotLightCount; // 0xD4
	public static int SpotLightPositions; // 0xD8
	public static int SpotLightDirections; // 0xDC
	public static int SpotLightColors; // 0xE0
	public static int BlueNoiseTexture; // 0xE4
	public static int DistantFogData; // 0xE8
	public static int BaseAltitude; // 0xEC
	public static int CullMode; // 0xF0
	public const string SKW_CUSTOM_DEPTH_ALPHA_TEST = "DEPTH_PREPASS_ALPHA_TEST";
	public const string SKW_SHAPE_BOX = "VF2_SHAPE_BOX";
	public const string SKW_SHAPE_SPHERE = "VF2_SHAPE_SPHERE";
	public const string SKW_POINT_LIGHTS = "VF2_POINT_LIGHTS";
	public const string SKW_NATIVE_LIGHTS = "VF2_NATIVE_LIGHTS";
	public const string SKW_VOIDS = "VF2_VOIDS";
	public const string SKW_FOW = "VF2_FOW";
	public const string SKW_RECEIVE_SHADOWS = "VF2_RECEIVE_SHADOWS";
	public const string SKW_DISTANCE = "VF2_DISTANCE";
	public const string SKW_CONSTANT_DENSITY = "VF2_CONSTANT_DENSITY";
	public const string SKW_DETAIL_NOISE = "VF2_DETAIL_NOISE";
	public const string SKW_SURFACE = "VF2_SURFACE";
	public const string SKW_DEPTH_PREPASS = "VF2_DEPTH_PREPASS";
	public const string SKW_DEPTH_GRADIENT = "VF2_DEPTH_GRADIENT";
	public const string SKW_HEIGHT_GRADIENT = "VF2_HEIGHT_GRADIENT";
	public const string SKW_DIRECTIONAL_COOKIE = "VF2_LIGHT_COOKIE";
	public const string SKW_APV = "VF2_APV";
	public const string SKW_DIFFUSION_SMOOTH = "VF2_DIFFUSION_SMOOTH";
	public const string SKW_DIFFUSION_STRONG = "VF2_DIFFUSION_STRONG";

	// Methods

	// RVA: 0x2ABECB0 Offset: 0x2ABD6B0 VA: 0x182ABECB0
	private static void .cctor() { }
}
