internal enum TOPTABITEMRIGHTEDGESTATES // TypeDefIndex: 6049
{
	// Fields
	public int value__; // 0x0
	public const TOPTABITEMRIGHTEDGESTATES TTIRES_NORMAL = 1;
	public const TOPTABITEMRIGHTEDGESTATES TTIRES_HOT = 2;
	public const TOPTABITEMRIGHTEDGESTATES TTIRES_SELECTED = 3;
	public const TOPTABITEMRIGHTEDGESTATES TTIRES_DISABLED = 4;
}
