internal enum TOPTABITEMLEFTEDGESTATES // TypeDefIndex: 6048
{
	// Fields
	public int value__; // 0x0
	public const TOPTABITEMLEFTEDGESTATES TTILES_NORMAL = 1;
	public const TOPTABITEMLEFTEDGESTATES TTILES_HOT = 2;
	public const TOPTABITEMLEFTEDGESTATES TTILES_SELECTED = 3;
	public const TOPTABITEMLEFTEDGESTATES TTILES_DISABLED = 4;
}
