internal sealed class XmlTreeGen // TypeDefIndex: 13001
{
	// Fields
	private ArrayList _constraintNames; // 0x10
	private Hashtable _namespaces; // 0x18
	private Hashtable _autogenerated; // 0x20
	private Hashtable _prefixes; // 0x28
	private DataSet _ds; // 0x30
	private ArrayList _tables; // 0x38
	private ArrayList _relations; // 0x40
	private XmlDocument _dc; // 0x48
	private XmlElement _sRoot; // 0x50
	private int _prefixCount; // 0x58
	private SchemaFormat _schFormat; // 0x5C
	private string _filePath; // 0x60
	private string _fileName; // 0x68
	private string _fileExt; // 0x70
	private XmlElement _dsElement; // 0x78
	private XmlElement _constraintSeparator; // 0x80
	private Converter<Type, string> _targetConverter; // 0x88

	// Methods

	// RVA: 0x20DDA60 Offset: 0x20DC460 VA: 0x1820DDA60
	internal void .ctor(SchemaFormat format) { }

	// RVA: 0x20D0A20 Offset: 0x20CF420 VA: 0x1820D0A20
	internal static void AddExtendedProperties(PropertyCollection props, XmlElement node) { }

	// RVA: 0x20D0A30 Offset: 0x20CF430 VA: 0x1820D0A30
	internal static void AddExtendedProperties(PropertyCollection props, XmlElement node, Type type) { }

	// RVA: 0x20D1030 Offset: 0x20CFA30 VA: 0x1820D1030
	internal void AddXdoProperties(object instance, XmlElement root, XmlDocument xd) { }

	// RVA: 0x20D11F0 Offset: 0x20CFBF0 VA: 0x1820D11F0
	internal void AddXdoProperty(PropertyDescriptor pd, object instance, XmlElement root, XmlDocument xd) { }

	// RVA: 0x20DCCE0 Offset: 0x20DB6E0 VA: 0x1820DCCE0
	internal static string XmlDataTypeName(Type type) { }

	// RVA: 0x20D3C00 Offset: 0x20D2600 VA: 0x1820D3C00
	private void GenerateConstraintNames(DataTable table, bool fromTable) { }

	// RVA: 0x20D3900 Offset: 0x20D2300 VA: 0x1820D3900
	private void GenerateConstraintNames(ArrayList tables) { }

	// RVA: 0x20D39F0 Offset: 0x20D23F0 VA: 0x1820D39F0
	private void GenerateConstraintNames(DataSet ds) { }

	// RVA: 0x20DDA30 Offset: 0x20DC430 VA: 0x1820DDA30
	private static bool _PropsNotEmpty(PropertyCollection props) { }

	// RVA: 0x20D8690 Offset: 0x20D7090 VA: 0x1820D8690
	private bool HaveExtendedProperties(DataSet ds) { }

	// RVA: 0x20DCAB0 Offset: 0x20DB4B0 VA: 0x1820DCAB0
	internal void WriteSchemaRoot(XmlDocument xd, XmlElement rootSchema, string targetNamespace) { }

	// RVA: 0x20DCA30 Offset: 0x20DB430 VA: 0x1820DCA30
	internal static void ValidateColumnMapping(Type columnType) { }

	// RVA: 0x20DBCC0 Offset: 0x20DA6C0 VA: 0x1820DBCC0
	internal void SetupAutoGenerated(DataSet ds) { }

	// RVA: 0x20DC850 Offset: 0x20DB250 VA: 0x1820DC850
	internal void SetupAutoGenerated(ArrayList dt) { }

	// RVA: 0x20DBED0 Offset: 0x20DA8D0 VA: 0x1820DBED0
	internal void SetupAutoGenerated(DataTable dt) { }

	// RVA: 0x20D27C0 Offset: 0x20D11C0 VA: 0x1820D27C0
	private void CreateTablesHierarchy(DataTable dt) { }

	// RVA: 0x20D2520 Offset: 0x20D0F20 VA: 0x1820D2520
	private void CreateRelations(DataTable dt) { }

	// RVA: 0x20D2A90 Offset: 0x20D1490 VA: 0x1820D2A90
	private DataTable[] CreateToplevelTables() { }

	// RVA: 0x20D91D0 Offset: 0x20D7BD0 VA: 0x1820D91D0
	internal void SchemaTree(XmlDocument xd, XmlWriter xmlWriter, DataSet ds, DataTable dt, bool writeHierarchy) { }

	// RVA: 0x20D8CA0 Offset: 0x20D76A0 VA: 0x1820D8CA0
	internal XmlElement SchemaTree(XmlDocument xd, DataTable dt) { }

	// RVA: 0x20D2D90 Offset: 0x20D1790 VA: 0x1820D2D90
	internal XmlElement FillDataSetElement(XmlDocument xd, DataSet ds, DataTable dt) { }

	// RVA: 0x20DBA20 Offset: 0x20DA420 VA: 0x1820DBA20
	internal void SetPath(XmlWriter xw) { }

	// RVA: 0x20D8BA0 Offset: 0x20D75A0 VA: 0x1820D8BA0
	internal void Save(DataSet ds, XmlWriter xw) { }

	// RVA: 0x20D8BD0 Offset: 0x20D75D0 VA: 0x1820D8BD0
	internal void Save(DataTable dt, XmlWriter xw) { }

	// RVA: 0x20D8A20 Offset: 0x20D7420 VA: 0x1820D8A20
	internal void Save(DataSet ds, DataTable dt, XmlWriter xw) { }

	// RVA: 0x20D88C0 Offset: 0x20D72C0 VA: 0x1820D88C0
	internal void Save(DataSet ds, DataTable dt, XmlWriter xw, bool writeHierarchy) { }

	// RVA: 0x20D8A40 Offset: 0x20D7440 VA: 0x1820D8A40
	internal void Save(DataSet ds, DataTable dt, XmlWriter xw, bool writeHierarchy, Converter<Type, string> multipleTargetConverter) { }

	// RVA: 0x20D52D0 Offset: 0x20D3CD0 VA: 0x1820D52D0
	internal XmlElement HandleRelation(DataRelation rel, XmlDocument dc) { }

	// RVA: 0x20D34C0 Offset: 0x20D1EC0 VA: 0x1820D34C0
	private static XmlElement FindSimpleType(XmlElement schema, string name) { }

	// RVA: 0x20D4010 Offset: 0x20D2A10 VA: 0x1820D4010
	internal XmlElement GetSchema(string NamespaceURI) { }

	// RVA: 0x20D42B0 Offset: 0x20D2CB0 VA: 0x1820D42B0
	internal void HandleColumnType(DataColumn col, XmlDocument dc, XmlElement root, XmlElement schema) { }

	// RVA: 0x20D03A0 Offset: 0x20CEDA0 VA: 0x1820D03A0
	internal void AddColumnProperties(DataColumn col, XmlElement root) { }

	// RVA: 0x20D35F0 Offset: 0x20D1FF0 VA: 0x1820D35F0
	private string FindTargetNamespace(DataTable table) { }

	// RVA: 0x20D4770 Offset: 0x20D3170 VA: 0x1820D4770
	internal XmlElement HandleColumn(DataColumn col, XmlDocument dc, XmlElement schema, bool fWriteOrdinal) { }

	// RVA: 0x20DC930 Offset: 0x20DB330 VA: 0x1820DC930
	internal static string TranslateAcceptRejectRule(AcceptRejectRule rule) { }

	// RVA: 0x20DC990 Offset: 0x20DB390 VA: 0x1820DC990
	internal static string TranslateRule(Rule rule) { }

	// RVA: 0x20D1BD0 Offset: 0x20D05D0 VA: 0x1820D1BD0
	internal void AppendChildWithoutRef(XmlElement node, string Namespace, XmlElement el, string refString) { }

	// RVA: 0x20D3710 Offset: 0x20D2110 VA: 0x1820D3710
	internal XmlElement FindTypeNode(XmlElement node, string strType) { }

	// RVA: 0x20D8420 Offset: 0x20D6E20 VA: 0x1820D8420
	internal XmlElement HandleTable(DataTable table, XmlDocument dc, XmlElement schema) { }

	// RVA: 0x20D8440 Offset: 0x20D6E40 VA: 0x1820D8440
	private bool HasMixedColumns(DataTable table) { }

	// RVA: 0x20D20F0 Offset: 0x20D0AF0 VA: 0x1820D20F0
	internal static bool AutoGenerated(DataColumn col) { }

	// RVA: 0x20D1FD0 Offset: 0x20D09D0 VA: 0x1820D1FD0
	internal static bool AutoGenerated(DataRelation rel) { }

	// RVA: 0x20D1C90 Offset: 0x20D0690 VA: 0x1820D1C90
	internal static bool AutoGenerated(UniqueConstraint unique) { }

	// RVA: 0x20D1D70 Offset: 0x20D0770 VA: 0x1820D1D70
	private bool AutoGenerated(ForeignKeyConstraint fk) { }

	// RVA: 0x20D1D80 Offset: 0x20D0780 VA: 0x1820D1D80
	internal static bool AutoGenerated(ForeignKeyConstraint fk, bool checkRelation) { }

	// RVA: 0x20D8880 Offset: 0x20D7280 VA: 0x1820D8880
	private bool IsAutoGenerated(object o) { }

	// RVA: 0x20D58F0 Offset: 0x20D42F0 VA: 0x1820D58F0
	internal XmlElement HandleTable(DataTable table, XmlDocument dc, XmlElement schema, bool genNested) { }

	// RVA: 0x20DB840 Offset: 0x20DA240 VA: 0x1820DB840
	private void SetMSDataAttribute(XmlElement root, Type type) { }
}
